const base="https://petaloverflow.github.io/tarot-api/cards/";
const majors=["愚人","魔术师","女祭司","皇后","皇帝","教皇","恋人","战车","力量","隐者","命运之轮","正义","倒吊人","死神","节制","恶魔","高塔","星星","月亮","太阳","审判","世界"];
const suits=[["wa","权杖"],["cu","圣杯"],["sw","宝剑"],["pe","星币"]];
const ranks=["王牌","二","三","四","五","六","七","八","九","十","侍从","骑士","皇后","国王"];
const cards=[...majors.map((name,i)=>({name,code:"ar"+String(i).padStart(2,"0"),type:"大阿尔卡那"})),...suits.flatMap(([p,s])=>ranks.map((r,i)=>({name:s+r,code:p+String(i+1).padStart(2,"0"),type:"小阿尔卡那"})))];
const spread=document.querySelector("#spread"),result=document.querySelector("#result"),hint=document.querySelector("#drawHint");let draw=[];
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function fan(){draw=shuffle(cards).slice(0,7);spread.innerHTML="";[-31,-21,-11,0,11,21,31].forEach((a,i)=>{const b=document.createElement("button");b.className="tarot-choice";b.type="button";b.ariaLabel="选择第 "+(i+1)+" 张塔罗牌";b.style.transform="translateX(-50%) rotate("+a+"deg)";b.style.left=(50+a*1.18)+"%";b.innerHTML='<span class="card-back"><span class="moon">☾</span><span class="card-back-title">TAROT</span></span>';b.onclick=()=>reveal(draw[i]);spread.append(b)})}
function reveal(c){[...spread.querySelectorAll("button")].forEach(x=>x.disabled=true);setTimeout(()=>{const rev=Math.random()<.32;document.querySelector("#cardNumber").textContent=c.type==="大阿尔卡那"?c.code.slice(2):"";const img=document.querySelector("#cardImage");img.src=base+c.code+".jpg";img.alt=c.name;document.querySelector("#cardNameOnCard").textContent=c.name;document.querySelector("#cardName").textContent=c.name;document.querySelector("#orientation").textContent=rev?"逆位 · 需要留意":"正位 · 今日指引";document.querySelector("#keywords").textContent=c.type+" · Rider–Waite–Smith";document.querySelector("#meaning").textContent=rev?"请放慢脚步，留意内在阻力与尚未被看见的需求。":"请相信你的直觉，观察此刻最值得回应的线索。";document.querySelector("#cardFace").style.transform=rev?"rotate(180deg)":"none";spread.style.display="none";hint.style.display="none";result.classList.remove("is-hidden")},450)}
document.querySelector("#againButton").onclick=()=>{result.classList.add("is-hidden");spread.style.display="block";hint.style.display="block";fan()};fan();
